### ISSUE TITLE
Package search functionality crashes the application

### ISSUE THREAD

**Issue by ispasmihai** [smathot/python-qtpip#1]
I use python 2.7 and pip 18.1.

Side note: The application started only after I installed also QtPy 1.9.0 with pip.

If the introduced input does not match any package, meaning the result list is empty, the following error occurs (eg. input for crashing the application: "abcxyz"):
```
Traceback (most recent call last):
  File "c:\work\git\software_dev\common\ext-tools\python\lib\site-packages\qtpip\decorators.py", line 30, in inner
    retval = fnc(*args, **kwargs)
  File "c:\work\git\software_dev\common\ext-tools\python\lib\site-packages\qtpip\_qpipwidget.py", line 62, in search
    self.ui.qdm.set_pkglist(self.pm.search(query))
  File "c:\work\git\software_dev\common\ext-tools\python\lib\site-packages\qtpip\_qpackagematrix.py", line 66, in set_pkglist
    for i, pkg in enumerate(pkglist):
  File "c:\work\git\software_dev\common\ext-tools\python\lib\site-packages\qtpip\_packagemanager.py", line 55, in search
    for name in utils.search_pypi(*query.lower().split()):
TypeError: 'NoneType' object is not iterable
```

**Comment by smathot** [comment]
Thanks for reporting this!
